mqtt_info:
  client_id: id-1003
  username: admin
  password: admin
  broker: localhost
  port: 1883
devices:
  - id: 8
    ip: google.com
  - id: 9
    ip: google.com
  - id: 10
    ip: 172.20.10.9
  - id: 11
    ip: 172.20.10.2
