sensors:
  cpu_usage:
    id: 1
    high: 80
    low: 20
  memory_usage:
    id: 2
    high: 80
    low: 20
  frames_per_second:
    id: 3
    high : 30
    low: 10
  objects_detected:
    id: 6
    high: 10
    low: 1
  cpu_temperature:
    id: 7
    high: 80
    low: 20
  ups_available:
    id: 8
    high: 1.5
    low: 0.5
  switch_available:
    id: 9
    high: 1.5
    low: 0.5
  camera_available:
    id: 10
    high: 1.5
    low: 0.5
  yolo_available:
    id: 11
    high: 1.5
    low: 0.5