faults:
  - id: 1
    name: "Black stream"
    symptoms: 
      - sensor_id: 6
        value: low
        temporal: progressive
    reasons:
      - name: "Camera is covered"
        action: "Uncover the camera"
  
  - id: 2
    name: "Black stream"
    symptoms:
    - sensor_id: 6
      value: low
      temporal: periodic
    reasons:
      - name: "Camera night vision failure"
        action: "Check the night vision"

  - id: 3
    name: "Black stream"
    symptoms:
      - sensor_id: 6
        value: low
        temporal: progressive
      - sensor_id: 3
        value: low
        temporal: progressive
      - sensor_id: 4
        value: low
        temporal: progressive
    reasons:
      - name: "Network failure"
        action: "Check the network connection"
  
  - id: 4
    name: "Cpu overheat"
    symptoms:
      - sensor_id: 7
        value: high
        temporal: progressive
    reasons:
      - name: "Fan is turned off"
        action: "Turn on the fan"
      - name: "High room temparature"
        action: "Cool down the room"

  - id: 5
    name: "Cpu overheat"
    symptoms:
      - sensor_id: 7
        value: high
        temporal: progressive
      - sensor_id: 1
        value: high
        temporal: progressive
    reasons:
      - name: "Intense cpu usage"
        action: "Scale up the resources"